export interface LLMResponse {
  success: boolean;
  data?: any;
  error?: string;
}

export const llmService = {
  async solveProblem(imageUrl: string): Promise<LLMResponse> {
    console.log(`[Mock LLM] Solving problem from image: ${imageUrl}`);
    // Mock delay
    await new Promise((resolve) => setTimeout(resolve, 1000));
    return {
      success: true,
      data: {
        solution: "This is a mocked solution generated by the LLM.",
        answer: "42",
      },
    };
  },

  async generateSubproblem(
    problemContent: any,
    hiddenSolution: string,
    userWork: any
  ): Promise<LLMResponse> {
    console.log("[Mock LLM] Generating subproblem based on user work...");
    await new Promise((resolve) => setTimeout(resolve, 1500));
    return {
      success: true,
      data: {
        student_summary: "The student understands basic algebra but missed the negative sign.",
        missing_insight: "Distributing the negative sign across parentheses.",
        subproblem_text: "Let's try a simpler one: What is -1 * (x - 5)?",
        tutor_message_intro: "I see what you did there. You're close, but watch your signs.",
        tutor_message_subproblem: "Try solving this smaller piece first to get the hang of it.",
        hidden_subproblem_solution: "-x + 5",
      },
    };
  },

  async checkThinking(
    problemContent: any,
    userWork: any
  ): Promise<LLMResponse> {
    console.log("[Mock LLM] Checking user thinking...");
    await new Promise((resolve) => setTimeout(resolve, 1000));
    return {
      success: true,
      data: {
        feedback: "You're on the right track! Remember to isolate the variable.",
      },
    };
  },

  async verifySubproblem(
    originalProblem: any,
    subproblem: any,
    userAttempt: any
  ): Promise<LLMResponse> {
    console.log("[Mock LLM] Verifying subproblem attempt...");
    await new Promise((resolve) => setTimeout(resolve, 1000));
    return {
      success: true,
      data: {
        solved: true,
        tutor_message: "Great job! Now apply that same logic to the original equation.",
      },
    };
  },
};
